{
  description = "Sindri OpenAI-Compatible JS SDK";

  inputs = {
    nixpkgs.url = "github:nixos/nixpkgs/nixos-25.05";
    flake-utils.url = "github:numtide/flake-utils";
    treefmt-nix = {
      url = "github:numtide/treefmt-nix";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };

  outputs =
    {
      self,
      nixpkgs,
      flake-utils,
      treefmt-nix,
    }:
    flake-utils.lib.eachDefaultSystem (
      system:
      let
        # Overlay to patch Go to always use Fetch API in WASM
        goWasmFetchOverlay = final: prev: {
          go_1_24 = prev.go_1_24.overrideAttrs (oldAttrs: {
            patches = (oldAttrs.patches or [ ]) ++ [
              (final.writeText "go-wasm-always-use-fetch.patch" ''
                --- a/src/net/http/roundtrip_js.go
                +++ b/src/net/http/roundtrip_js.go
                @@ -13,7 +13,6 @@ import (
                 	"io"
                 	"net/http/internal/ascii"
                 	"strconv"
                -	"strings"
                 	"syscall/js"
                 )
                 
                @@ -56,8 +55,8 @@ var jsFetchMissing = js.Global().Get("fetch").IsUndefined()
                 //
                 // TODO(go.dev/issue/60810): See if it's viable to test the Fetch API
                 // code path.
                -var jsFetchDisabled = js.Global().Get("process").Type() == js.TypeObject &&
                -	strings.HasPrefix(js.Global().Get("process").Get("argv0").String(), "node")
                +// Patched to always use Fetch API for better WASM compatibility in Node.js
                +var jsFetchDisabled = false
                 
                 // RoundTrip implements the [RoundTripper] interface using the WHATWG Fetch API.
                 func (t *Transport) RoundTrip(req *Request) (*Response, error) {
              '')
            ];
          });
        };

        # Apply overlay to get patched Go
        pkgs = import nixpkgs {
          inherit system;
          overlays = [ goWasmFetchOverlay ];
        };

        go = pkgs.go_1_24;
        nodejs = pkgs.nodejs_22;

        # Treefmt config.
        treefmtEval = treefmt-nix.lib.evalModule pkgs {
          projectRootFile = "flake.nix";

          # Go formatters.
          programs.gofumpt.enable = true;
          programs.goimports.enable = true;

          # Nix formatters.
          programs.nixfmt.enable = true;
          programs.deadnix.enable = true;
          programs.statix.enable = true;
        };

        # Package for the OpenAI SDK build.
        openai-sdk = pkgs.stdenv.mkDerivation {
          pname = "openai-sdk";
          inherit ((pkgs.lib.importJSON ./package.json)) version;

          src = pkgs.lib.cleanSourceWith {
            src = ./.;
            filter = _path: _type: true;
          };

          nativeBuildInputs = [
            pkgs.bash
            go
            nodejs
            pkgs.yarn
            pkgs.yarnConfigHook
          ];

          yarnOfflineCache = pkgs.fetchYarnDeps {
            yarnLock = ./yarn.lock;
            hash = "sha256-8LxXXALIlx/ThTLTTsMmgtp4BypveV7cBh7eroZnUUo=";
          };

          buildPhase = ''
            runHook preBuild

            # Patch shebangs in scripts to use correct bash path.
            patchShebangs scripts/

            # Build the TypeScript code normally without any modifications.
            # This will build everything including the stub WASM files.
            yarn build

            # Now build the Go WASM module.
            export HOME=$TMPDIR
            export GOCACHE=$TMPDIR/go-cache
            export GOPATH=$TMPDIR/go
            export GOOS=js
            export GOARCH=wasm

            echo "Building Go WASM module..."
            pushd go
            go build -mod=vendor -tags wasm -o main.wasm .
            popd

            # Now copy real WASM files over the stubs in the dist directory.
            echo "Replacing stub WASM files with real ones..."

            # Create the wasm directory in dist.
            mkdir -p dist/sindri/wasm

            # Embed the WASM as base64 in wasm.js.
            echo "Embedding WASM as base64..."

            # Create wasm.js with embedded base64 WASM.
            echo "// WASM module with embedded binary as base64." > dist/sindri/wasm/wasm.js
            echo "// This file is auto-generated by the build process." >> dist/sindri/wasm/wasm.js
            echo "" >> dist/sindri/wasm/wasm.js
            echo -n "const wasmBase64 = \"" >> dist/sindri/wasm/wasm.js

            # Append the base64-encoded WASM inline.
            base64 -w 0 go/main.wasm >> dist/sindri/wasm/wasm.js

            # Close the string and add the decoder function.
            echo "\";" >> dist/sindri/wasm/wasm.js
            echo "" >> dist/sindri/wasm/wasm.js
            echo "function getWasmBytes() {" >> dist/sindri/wasm/wasm.js
            echo "  // Decode base64 to binary." >> dist/sindri/wasm/wasm.js
            echo "  const binaryString = atob(wasmBase64);" >> dist/sindri/wasm/wasm.js
            echo "  const bytes = new Uint8Array(binaryString.length);" >> dist/sindri/wasm/wasm.js
            echo "  for (let i = 0; i < binaryString.length; i++) {" >> dist/sindri/wasm/wasm.js
            echo "    bytes[i] = binaryString.charCodeAt(i);" >> dist/sindri/wasm/wasm.js
            echo "  }" >> dist/sindri/wasm/wasm.js
            echo "  return bytes;" >> dist/sindri/wasm/wasm.js
            echo "}" >> dist/sindri/wasm/wasm.js
            echo "" >> dist/sindri/wasm/wasm.js
            echo "module.exports = { getWasmBytes };" >> dist/sindri/wasm/wasm.js

            # Create wasm.mjs for ESM with embedded base64.
            echo "// WASM module with embedded binary as base64." > dist/sindri/wasm/wasm.mjs
            echo "// This file is auto-generated by the build process." >> dist/sindri/wasm/wasm.mjs
            echo "" >> dist/sindri/wasm/wasm.mjs
            echo -n "const wasmBase64 = \"" >> dist/sindri/wasm/wasm.mjs

            # Append the base64-encoded WASM inline.
            base64 -w 0 go/main.wasm >> dist/sindri/wasm/wasm.mjs

            # Close the string and add the decoder function.
            echo "\";" >> dist/sindri/wasm/wasm.mjs
            echo "" >> dist/sindri/wasm/wasm.mjs
            echo "export function getWasmBytes() {" >> dist/sindri/wasm/wasm.mjs
            echo "  // Decode base64 to binary." >> dist/sindri/wasm/wasm.mjs
            echo "  const binaryString = atob(wasmBase64);" >> dist/sindri/wasm/wasm.mjs
            echo "  const bytes = new Uint8Array(binaryString.length);" >> dist/sindri/wasm/wasm.mjs
            echo "  for (let i = 0; i < binaryString.length; i++) {" >> dist/sindri/wasm/wasm.mjs
            echo "    bytes[i] = binaryString.charCodeAt(i);" >> dist/sindri/wasm/wasm.mjs
            echo "  }" >> dist/sindri/wasm/wasm.mjs
            echo "  return bytes;" >> dist/sindri/wasm/wasm.mjs
            echo "}" >> dist/sindri/wasm/wasm.mjs

            # Copy the real Go wasm_exec.js runtime.
            cp "${go}/share/go/lib/wasm/wasm_exec.js" dist/sindri/wasm/wasm_exec.js
            cp "${go}/share/go/lib/wasm/wasm_exec.js" dist/sindri/wasm/wasm_exec.mjs

            runHook postBuild
          '';

          installPhase = ''
            runHook preInstall

            # Copy the built dist directory to output.
            mkdir -p $out
            cp -r dist/* $out/

            runHook postInstall
          '';
        };

      in
      {
        packages.default = openai-sdk;

        formatter = treefmtEval.config.build.wrapper;
        checks.formatting = treefmtEval.config.build.check self;

        devShells.default = pkgs.mkShell {
          buildInputs = with pkgs; [

            # Go tools.
            delve
            go
            go-tools
            gofumpt
            golangci-lint
            gopls

            # Node tools.
            nodejs
            yarn

            # Nix tools.
            deadnix
            nil
            nixfmt-rfc-style
            statix
            treefmtEval.config.build.wrapper

            # WASM optimization tools.
            binaryen
            wabt
          ];

          shellHook = ''
            # Install JS dependencies locally.
            yarn install

            # Add node_modules/.bin to PATH for JS linting, formatting, etc.
            export PATH="$PWD/node_modules/.bin:$PATH"

            # Set GOPATH if not already set.
            export GOPATH="''${GOPATH:-$HOME/go}"
            export PATH="$GOPATH/bin:$PATH"

            # Ensure WASM builds by default.
            export GOOS=js
            export GOARCH=wasm

            echo ""
            echo "Sindri OpenAI-Compatible JS SDK Development Environment"
            echo "======================================================"
            echo "Go version: $(go version)"
            echo "Node version: $(node --version)"
            echo "Yarn version: $(yarn --version)"
            echo ""

          '';
        };
      }
    );
}
