name: Sindri CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run flake checks
        run: nix flake check

  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the package
        run: nix build

      - name: Verify build outputs exist
        run: |
          # Check that the build created the expected directory structure.
          test -d result/
          test -d result/sindri/
          test -d result/sindri/wasm/

      - name: Verify WASM module files
        run: |
          # Verify WASM files were generated with embedded base64.
          test -f result/sindri/wasm/wasm.js
          test -f result/sindri/wasm/wasm.mjs

          # Verify TinyGo runtime files.
          test -f result/sindri/wasm/wasm_exec.js
          test -f result/sindri/wasm/wasm_exec.mjs

          # Check that base64 was actually embedded (not placeholder).
          if grep -q "WASM_MODULE_PLACEHOLDER" result/sindri/wasm/wasm.js; then
            echo "Error: WASM module was not properly embedded"
            exit 1
          fi

      - name: Verify TypeScript compilation
        run: |
          # Check that TypeScript files were compiled.
          test -f result/index.js
          test -f result/index.d.ts
          test -f result/sindri/index.js
          test -f result/sindri/index.d.ts
